const appname = 'eApp';
const appversion = 'Version 1.0.0';
const credits = '@Anne';
const email = 'Email';
const emailHint = 'admin@gmail.com';
const password = 'Password';  // Corrected variable name
const passwordHint = '******';  // Corrected variable name
const forgetPassword = 'forget password';
const login = 'Log in';
const signup = ' Sign up';
const createNewAccount = 'or, create a new account';
const loginWith = ' Log in with';
